# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
disabled = true

[gcloud]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
