# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
disabled = true

[docker_context]
disabled = true

[python]
disabled = true

[gcloud]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
disabled = true
